name: Doxygen Install, Generate, and Commit

on:
  push:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Doxyfile
        run: doxygen -g
        
      - name: list Doxyfile
        run: pwd && ls -al

      - name: Commit and push if changes
        run: |
          git add .
          git remote add origin git@github.com:ramen4598/action_test.git
          git commit -m "Generate Doxyfile" && git push
